### ISSUE TITLE
I installed the latest os 11701, and my op 1 is bricked...

### ISSUE THREAD

**Issue by forg-man** [op1hacks/op1-fw-archive#5]
I cant start it up even with com mode I get no response, thus I cant uninstall the latest os as I need com mode to make it accessible.the only response I get is when its first plugged in, the lights light up in order and all of them stay on before briefly turning off. 

I understand this might no be an official thing but you can imagine how one might feel after turning their wonderful synthesizer into a potato. 

on the other note if this was a scam or a prank you did some amazing work. now go suck an egg.

**Comment by forg-man** [comment]
ah I now see that I installed the oldest os which should probably break things. either way if you have any idea how I can revive my op 1 please leave your input

**Comment by Nick-Heyart** [comment]
I was able to get the original fw working by deleting user data via the bootloader menu, since the newer fw saves data for synths that don't even exist on the original fw.
